version: "3.3"

services:
  api:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin

